<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DriveMigrator.Providers.Google</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Google.Apis.Auth" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DriveMigrator.Core\DriveMigrator.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="DriveMigrator.Providers.Tests" />
  </ItemGroup>
</Project>
