<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\DriveMigrator.Providers.Google\DriveMigrator.Providers.Google.csproj" />
    <ProjectReference Include="..\..\src\DriveMigrator.Providers.Microsoft\DriveMigrator.Providers.Microsoft.csproj" />
  </ItemGroup>
</Project>
