<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DriveMigrator.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Identity.Client.Extensions.Msal" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DriveMigrator.Core\DriveMigrator.Core.csproj" />
  </ItemGroup>
</Project>
